#!/usr/bin/env bash
# Generate deploy/deploy.env from environment variables (GitHub Actions / CI).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/deploy/deploy.env}"

: "${DEPLOY_HOST:?Set DEPLOY_HOST}"
: "${DEPLOY_USER:?Set DEPLOY_USER}"
: "${DEPLOY_PATH:?Set DEPLOY_PATH}"

mkdir -p "$(dirname "$OUT")"

{
	echo "# Generated by deploy/write-deploy-env.sh — do not commit"
	echo "DEPLOY_HOST=${DEPLOY_HOST}"
	echo "DEPLOY_USER=${DEPLOY_USER}"
	echo "DEPLOY_PORT=${DEPLOY_PORT:-22}"
	echo "DEPLOY_PATH=${DEPLOY_PATH}"
	echo "DEPLOY_PUBLIC_URL=${DEPLOY_PUBLIC_URL:-https://${DEPLOY_HOST}}"
	echo "DEPLOY_RUN_USER=${DEPLOY_RUN_USER:-www}"
	echo "DEPLOY_FRONTEND=${DEPLOY_FRONTEND:-pm2}"
	echo "DEPLOY_PM2_USER=${DEPLOY_PM2_USER:-dianrp}"
	echo "DEPLOY_PM2_APP_NAME=${DEPLOY_PM2_APP_NAME:-kasq-fe}"
	echo "DEPLOY_RESTART=${DEPLOY_RESTART:-true}"
	echo "DEPLOY_GOOS=${DEPLOY_GOOS:-linux}"
	echo "DEPLOY_GOARCH=${DEPLOY_GOARCH:-amd64}"
	echo "DEPLOY_STRIP_SOURCEMAPS=${DEPLOY_STRIP_SOURCEMAPS:-true}"
	echo "DEPLOY_RSYNC_COMPRESS=${DEPLOY_RSYNC_COMPRESS:-true}"
	echo "DEPLOY_SKIP_NPM_CI=${DEPLOY_SKIP_NPM_CI:-false}"
	echo "DEPLOY_PARALLEL_BUILD=${DEPLOY_PARALLEL_BUILD:-true}"
	echo "DEPLOY_ONLY=${DEPLOY_ONLY:-all}"
	if [[ -n "${DEPLOY_SSH_KEY:-}" ]]; then
		echo "DEPLOY_SSH_KEY=${DEPLOY_SSH_KEY}"
	fi
	if [[ -n "${DEPLOY_PM2_BIN:-}" ]]; then
		echo "DEPLOY_PM2_BIN=${DEPLOY_PM2_BIN}"
	fi
} >"$OUT"

echo "Wrote ${OUT}"
